# Site settings
language:               ""
title:                  "Gottlieb Group"
description:            "The Gottlieb Group develops and improves ideas and strategies to advance market opportunities and to improve community initiatives."
google-verification:    ""

# Handling Reading
include:
  - ".htaccess"
  - "_pages"

exclude:
  - "/assets/"
  - "bower.json"
  - "composer.json"
  - "composer.lock"
  - "DOC.md"
  - "Gemfile"
  - "Gemfile.lock"
  - "/gulp/"
  - "gulpfile.js"
  - "LICENSE.md"
  - "Makefile"
  - "node_modules"
  - "npm-debug.log"
  - "package.json"
  - "README.md"
  - "rev-manifest.json"
  - "yarn.lock"

# Plugins
# Add plugins in the Gemfile

# Conversion
incremental:      true

# Serving
# url:            ""
# baseurl:        "" # does not include hostname

# Outputting
permalink:        "/articles/:year/:title/"
paginate_path:    "/articles/page:num"
paginate:         5

compress_html:
  ignore:
    envs: [development]

highlighter:      rouge
